// ============================================================================
// NYAYAAI FICTIONAL DEMONSTRATION LEGAL DATABASE
// NOTICE: ALL ENTRIES ARE STRICTLY FICTIONAL DEMONSTRATION DATA
// ============================================================================

import {
  LegalSource,
  CaseRecord,
  DocumentRecord,
  ResearchSession,
  JudgmentAnalysis,
  User,
  Organization,
  SubscriptionInfo,
  AIUsageMetrics,
  AuditLogEntry
} from "@/types";

export const DEMO_USERS: User[] = [
  {
    id: "user-advocate-01",
    name: "Adv. Rajesh V. Nariman (Demo)",
    email: "demo.advocate@nyayaai.test",
    role: "Partner",
    category: "Advocate",
    state: "Delhi NCR",
    practiceAreas: ["Constitutional Law", "Criminal Law (BNS/BNSS)", "Commercial Arbitration"],
    organizationId: "org-demo-firm-01",
    organizationName: "Lex Indica Law Chambers (Demo)",
    createdAt: "2024-01-15T09:00:00Z",
    isDemo: true,
  },
  {
    id: "user-admin-01",
    name: "Dr. Priyamvada Iyer (Demo Admin)",
    email: "demo.admin@nyayaai.test",
    role: "Admin",
    category: "Law Firm Admin",
    state: "Maharashtra",
    practiceAreas: ["Corporate Governance", "Litigation Management", "Insolvency & Bankruptcy"],
    organizationId: "org-demo-firm-01",
    organizationName: "Lex Indica Law Chambers (Demo)",
    createdAt: "2024-01-10T08:30:00Z",
    isDemo: true,
  },
  {
    id: "user-associate-01",
    name: "Arjun S. Mehra (Associate)",
    email: "demo.associate@nyayaai.test",
    role: "Associate",
    category: "Advocate",
    state: "Karnataka",
    practiceAreas: ["Intellectual Property", "IT & Data Privacy"],
    organizationId: "org-demo-firm-01",
    organizationName: "Lex Indica Law Chambers (Demo)",
    createdAt: "2024-02-01T10:00:00Z",
    isDemo: true,
  }
];

export const DEMO_ORGANIZATION: Organization = {
  id: "org-demo-firm-01",
  name: "Lex Indica Law Chambers (Demo)",
  planId: "professional",
  memberCount: 8,
  createdAt: "2024-01-10T08:30:00Z",
  isDemo: true,
};

export const DEMO_SUBSCRIPTION: SubscriptionInfo = {
  organizationId: "org-demo-firm-01",
  planId: "professional",
  planName: "Professional Chambers",
  amountInr: 2499,
  billingCycle: "monthly",
  status: "active",
  currentPeriodEnd: "2026-10-15T23:59:59Z",
  provider: "mock",
};

export const DEMO_AI_USAGE: AIUsageMetrics = {
  organizationId: "org-demo-firm-01",
  periodMonth: "September 2026",
  researchQueriesUsed: 142,
  researchQueriesLimit: 2000,
  documentAnalysesUsed: 28,
  documentAnalysesLimit: 100,
  draftsGeneratedUsed: 19,
  draftsGeneratedLimit: 150,
  citationChecksUsed: 84,
  citationChecksLimit: 1000,
  tokensConsumed: 184500,
};

// ============================================================================
// 22 FICTIONAL STATUTES (BNS, BNSS, BSA 2023 vs IPC, CrPC, IEA + Commercial Acts)
// ============================================================================
export interface StatuteRecord {
  id: string;
  title: string;
  actNumber: string;
  year: number;
  enactedBy: string;
  domain: string;
  isModern: boolean;
  historicalEquivalent?: string;
  keySections: { section: string; title: string; description: string }[];
  summary: string;
  demo: true;
}

export const DEMO_STATUTES: StatuteRecord[] = [
  {
    id: "stat-01",
    title: "Bharatiya Nyaya Sanhita, 2023 (BNS)",
    actNumber: "Act No. 45 of 2023",
    year: 2023,
    enactedBy: "Parliament of India",
    domain: "Substantive Criminal Law",
    isModern: true,
    historicalEquivalent: "Indian Penal Code, 1860 (IPC - Repealed/Historical)",
    keySections: [
      { section: "Section 103", title: "Punishment for murder", description: "Defines homicide amounting to murder; replaces IPC Section 302." },
      { section: "Section 111", title: "Organized crime", description: "New substantive provision codifying organized crime syndicates." },
      { section: "Section 316", title: "Criminal breach of trust", description: "Replaces IPC Section 405/406 with modernized entrustment provisions." },
      { section: "Section 318", title: "Cheating and dishonestly inducing delivery of property", description: "Replaces IPC Section 415/420." }
    ],
    summary: "Modern primary substantive criminal code of India replacing the Indian Penal Code, 1860.",
    demo: true,
  },
  {
    id: "stat-02",
    title: "Bharatiya Nagarik Suraksha Sanhita, 2023 (BNSS)",
    actNumber: "Act No. 46 of 2023",
    year: 2023,
    enactedBy: "Parliament of India",
    domain: "Criminal Procedural Law",
    isModern: true,
    historicalEquivalent: "Code of Criminal Procedure, 1973 (CrPC - Repealed/Historical)",
    keySections: [
      { section: "Section 35", title: "Arrest of persons and procedural protections", description: "Replaces CrPC Section 41; mandates objective reasoning and videography." },
      { section: "Section 173", title: "First Information Report (Zero FIR / e-FIR)", description: "Explicit statutory recognition of electronic reporting and jurisdiction-free Zero FIR." },
      { section: "Section 187", title: "Custody during investigation", description: "Procedural framework for police and judicial remand up to 15 or 60/90 days." },
      { section: "Section 480", title: "Bail in non-bailable offenses", description: "Modern equivalent of CrPC Section 437 governing magistrate discretion." },
      { section: "Section 482", title: "Special powers of High Court regarding bail", description: "Direct equivalent of CrPC Section 439 for anticipatory and regular bail." }
    ],
    summary: "Governs criminal procedure, investigation timelines, electronic evidence recording, and bail discretion.",
    demo: true,
  },
  {
    id: "stat-03",
    title: "Bharatiya Sakshya Adhiniyam, 2023 (BSA)",
    actNumber: "Act No. 47 of 2023",
    year: 2023,
    enactedBy: "Parliament of India",
    domain: "Law of Evidence",
    isModern: true,
    historicalEquivalent: "Indian Evidence Act, 1872 (IEA - Repealed/Historical)",
    keySections: [
      { section: "Section 61", title: "Admissibility of electronic or digital records", description: "Replaces IEA Section 65B; streamlines certificates and digital hash logs." },
      { section: "Section 63", title: "Conditions of admissibility of electronic records", description: "Technical certification prerequisites for server and device logs." },
      { section: "Section 114", title: "Presumption as to certain offenses", description: "Statutory presumptions on documentary execution." }
    ],
    summary: "Modernized evidentiary framework giving primary status to electronic and cryptographic records.",
    demo: true,
  },
  {
    id: "stat-04",
    title: "Arbitration and Conciliation Act, 1996 (as amended)",
    actNumber: "Act No. 26 of 1996",
    year: 1996,
    enactedBy: "Parliament of India",
    domain: "Alternative Dispute Resolution",
    isModern: true,
    keySections: [
      { section: "Section 9", title: "Interim measures by Court", description: "Pre-arbitration and pendente lite interim injunctions." },
      { section: "Section 11", title: "Appointment of arbitrators", description: "High Court and Supreme Court appointment jurisdiction." },
      { section: "Section 34", title: "Application for setting aside arbitral award", description: "Strict grounds limited to patent illegality and public policy." },
      { section: "Section 37", title: "Appealable orders", description: "Appellate scrutiny strictly constrained against merit re-examination." }
    ],
    summary: "Statutory charter for domestic and international commercial arbitrations seated in India.",
    demo: true,
  },
  {
    id: "stat-05",
    title: "Insolvency and Bankruptcy Code, 2016 (IBC)",
    actNumber: "Act No. 31 of 2016",
    year: 2016,
    enactedBy: "Parliament of India",
    domain: "Corporate Restructuring & Insolvency",
    isModern: true,
    keySections: [
      { section: "Section 7", title: "Initiation of CIRP by financial creditor", description: "Default-based corporate insolvency trigger." },
      { section: "Section 9", title: "Initiation of CIRP by operational creditor", description: "Pre-existing dispute threshold." },
      { section: "Section 14", title: "Moratorium", description: "Statutory injunction against proceedings during CIRP." },
      { section: "Section 31", title: "Approval of resolution plan", description: "Clean slate doctrine post NCLT approval." }
    ],
    summary: "Consolidated code for time-bound corporate insolvency resolution and liquidation.",
    demo: true,
  },
  {
    id: "stat-06",
    title: "Commercial Courts Act, 2015",
    actNumber: "Act No. 4 of 2016",
    year: 2015,
    enactedBy: "Parliament of India",
    domain: "Commercial Litigation",
    isModern: true,
    keySections: [
      { section: "Section 12A", title: "Pre-institution mediation and settlement", description: "Mandatory pre-litigation mediation unless urgent interim relief sought." },
      { section: "Section 13", title: "Appeals from decrees of Commercial Courts", description: "Appellate jurisdiction within 60 days." }
    ],
    summary: "Fast-track resolution of commercial disputes above specified monetary thresholds.",
    demo: true,
  },
  {
    id: "stat-07",
    title: "Information Technology Act, 2000 (with Digital Intermediary Rules)",
    actNumber: "Act No. 21 of 2000",
    year: 2000,
    enactedBy: "Parliament of India",
    domain: "Cyber & Technology Law",
    isModern: true,
    keySections: [
      { section: "Section 43A", title: "Compensation for failure to protect data", description: "Corporate liability for data leakage." },
      { section: "Section 66A", title: "Striken Down (Historical Reference)", description: "Historically invalidated in Shreya Singhal (2015)." },
      { section: "Section 79", title: "Exemption from liability of intermediary in certain cases", description: "Safe harbor doctrine subject to due diligence." }
    ],
    summary: "Cyber offenses, intermediary safe harbor, electronic signatures, and digital communications.",
    demo: true,
  },
  {
    id: "stat-08",
    title: "Digital Personal Data Protection Act, 2023 (DPDP)",
    actNumber: "Act No. 22 of 2023",
    year: 2023,
    enactedBy: "Parliament of India",
    domain: "Data Privacy Law",
    isModern: true,
    keySections: [
      { section: "Section 6", title: "Consent and notice requirements", description: "Specific, informed, unconditional consent for data fiduciaries." },
      { section: "Section 8", title: "General obligations of Data Fiduciary", description: "Reasonable security safeguards and mandatory breach notification." }
    ],
    summary: "India's statutory data protection framework governing digital personal data handling.",
    demo: true,
  },
  {
    id: "stat-09",
    title: "Companies Act, 2013",
    actNumber: "Act No. 18 of 2013",
    year: 2013,
    enactedBy: "Parliament of India",
    domain: "Corporate Law",
    isModern: true,
    keySections: [
      { section: "Section 166", title: "Duties of directors", description: "Statutory fiduciary duties towards company, employees, and community." },
      { section: "Section 241", title: "Application to Tribunal for relief in cases of oppression", description: "Minority shareholder protection before NCLT." }
    ],
    summary: "Comprehensive corporate legislation covering governance, directors' duties, and M&A.",
    demo: true,
  },
  {
    id: "stat-10",
    title: "Constitution of India (Selected Articles)",
    actNumber: "Constituent Assembly of India",
    year: 1950,
    enactedBy: "People of India",
    domain: "Constitutional Law",
    isModern: true,
    keySections: [
      { section: "Article 14", title: "Equality before law", description: "Prohibition of arbitrariness and requirement of reasonable classification." },
      { section: "Article 19(1)(g)", title: "Freedom of trade and profession", description: "Right to carry on any trade or occupation subject to reasonable restrictions." },
      { section: "Article 21", title: "Protection of life and personal liberty", description: "Substantive due process, fair procedure, privacy, and right to bail." },
      { section: "Article 226", title: "Power of High Courts to issue certain writs", description: "Extraordinary plenary writ jurisdiction for fundamental and legal rights." },
      { section: "Article 32", title: "Remedies for enforcement of rights conferred by Part III", description: "Supreme Court direct constitutional remedy." }
    ],
    summary: "The supreme grundnorm of Indian legal architecture establishing fundamental rights and judicial review.",
    demo: true,
  },
  {
    id: "stat-11",
    title: "Specific Relief Act, 1963 (as amended 2018)",
    actNumber: "Act No. 47 of 1963",
    year: 1963,
    enactedBy: "Parliament of India",
    domain: "Contract & Remedies",
    isModern: true,
    keySections: [
      { section: "Section 10", title: "Specific performance in respect of contracts", description: "Mandatory grant of specific performance replacing discretionary compensation." },
      { section: "Section 20A", title: "Special provisions for infrastructure projects", description: "Prohibition of injunctions causing delay in notified infrastructure projects." }
    ],
    summary: "Governs equitable remedies, injunctions, and specific performance of commercial contracts.",
    demo: true,
  },
  {
    id: "stat-12",
    title: "Prevention of Money Laundering Act, 2002 (PMLA)",
    actNumber: "Act No. 15 of 2003",
    year: 2002,
    enactedBy: "Parliament of India",
    domain: "Financial Crimes & Economic Offenses",
    isModern: true,
    keySections: [
      { section: "Section 3", title: "Offense of money laundering", description: "Broad definition encompassing projection of proceeds as untainted." },
      { section: "Section 24", title: "Burden of proof", description: "Reverse burden of proof on accused in court proceedings." },
      { section: "Section 45", title: "Offenses to be cognizable and non-bailable (Twin Conditions)", description: "Twin conditions of bail requiring judicial satisfaction of innocence." }
    ],
    summary: "Special anti-money laundering statute with stringent bail hurdles and asset attachment powers.",
    demo: true,
  },
  {
    id: "stat-13",
    title: "Consumer Protection Act, 2019",
    actNumber: "Act No. 35 of 2019",
    year: 2019,
    enactedBy: "Parliament of India",
    domain: "Consumer Law & Product Liability",
    isModern: true,
    keySections: [
      { section: "Section 82", title: "Product liability action", description: "Statutory product liability claims against manufacturers and sellers." }
    ],
    summary: "Modernized consumer dispute redressal with statutory product liability and e-commerce rules.",
    demo: true,
  },
  {
    id: "stat-14",
    title: "Negotiable Instruments Act, 1881 (NI Act)",
    actNumber: "Act No. 26 of 1881",
    year: 1881,
    enactedBy: "Central Legislative Assembly",
    domain: "Commercial Banking & Cheque Dishonour",
    isModern: true,
    keySections: [
      { section: "Section 138", title: "Dishonour of cheque for insufficiency, etc., of funds", description: "Quasi-criminal prosecution for dishonoured negotiable instruments." },
      { section: "Section 143A", title: "Power to direct interim compensation", description: "Discretion to order drawer to deposit up to 20% of cheque amount." }
    ],
    summary: "Governs bills of exchange, promissory notes, and statutory cheque bounce complaints.",
    demo: true,
  },
  {
    id: "stat-15",
    title: "Competition Act, 2002 (as amended 2023)",
    actNumber: "Act No. 12 of 2003",
    year: 2002,
    enactedBy: "Parliament of India",
    domain: "Antitrust & Competition",
    isModern: true,
    keySections: [
      { section: "Section 3", title: "Anti-competitive agreements", description: "Prohibits cartels and bid-rigging agreements." },
      { section: "Section 4", title: "Abuse of dominant position", description: "Prohibits predatory pricing and denial of market access." }
    ],
    summary: "Antitrust statute enforced by the Competition Commission of India.",
    demo: true,
  },
  {
    id: "stat-16",
    title: "Trade Marks Act, 1999",
    actNumber: "Act No. 47 of 1999",
    year: 1999,
    enactedBy: "Parliament of India",
    domain: "Intellectual Property",
    isModern: true,
    keySections: [
      { section: "Section 29", title: "Infringement of registered trade marks", description: "Deceptive similarity and dilution of well-known marks." }
    ],
    summary: "Protection of registered trademarks, passing off actions, and commercial brand disputes.",
    demo: true,
  },
  {
    id: "stat-17",
    title: "Indian Contract Act, 1872",
    actNumber: "Act No. 9 of 1872",
    year: 1872,
    enactedBy: "Central Legislative Council",
    domain: "Contract Law",
    isModern: true,
    keySections: [
      { section: "Section 23", title: "What considerations and objects are lawful", description: "Contracts void for public policy or statutory contravention." },
      { section: "Section 73", title: "Compensation for loss or damage caused by breach", description: "Direct damages and remoteness of consequences." },
      { section: "Section 74", title: "Compensation for breach of contract where penalty stipulated", description: "Reasonable compensation not exceeding liquidated damages." }
    ],
    summary: "Core substantive legislation governing offer, acceptance, consideration, breach, and indemnity.",
    demo: true,
  },
  {
    id: "stat-18",
    title: "Transfer of Property Act, 1882",
    actNumber: "Act No. 4 of 1882",
    year: 1882,
    enactedBy: "Governor-General of India",
    domain: "Real Estate & Property Law",
    isModern: true,
    keySections: [
      { section: "Section 53A", title: "Part performance", description: "Equitable protection of transferee in possession under written contract." },
      { section: "Section 106", title: "Duration of certain leases in absence of written contract", description: "Statutory notice periods for terminating commercial leases." }
    ],
    summary: "Rules governing sale, mortgage, lease, exchange, and gift of immovable property.",
    demo: true,
  },
  {
    id: "stat-19",
    title: "Right to Fair Compensation in Land Acquisition (RFCTLARR) Act, 2013",
    actNumber: "Act No. 30 of 2013",
    year: 2013,
    enactedBy: "Parliament of India",
    domain: "Land Acquisition & Infrastructure",
    isModern: true,
    keySections: [
      { section: "Section 24", title: "Land acquisition process under Act No. 1 of 1894 when deemed lapsed", description: "Five-year physical possession and compensation deposit thresholds." }
    ],
    summary: "Governs mandatory rehabilitation, resettlement, and statutory compensation multiples.",
    demo: true,
  },
  {
    id: "stat-20",
    title: "Real Estate (Regulation and Development) Act, 2016 (RERA)",
    actNumber: "Act No. 16 of 2016",
    year: 2016,
    enactedBy: "Parliament of India",
    domain: "Real Estate & Homebuyer Protection",
    isModern: true,
    keySections: [
      { section: "Section 18", title: "Return of amount and compensation", description: "Statutory right of homebuyer to refund with interest upon project delay." }
    ],
    summary: "Protects homebuyers against delayed possession and diversion of escrow funds.",
    demo: true,
  },
  {
    id: "stat-21",
    title: "Code of Civil Procedure, 1908 (CPC)",
    actNumber: "Act No. 5 of 1908",
    year: 1908,
    enactedBy: "Central Legislative Council",
    domain: "Civil Procedural Law",
    isModern: true,
    keySections: [
      { section: "Order VII Rule 11", title: "Rejection of plaint", description: "Summary disposal where plaint discloses no cause of action or is barred by law." },
      { section: "Order XXXIX Rules 1 & 2", title: "Temporary injunctions", description: "Prima facie case, balance of convenience, and irreparable injury triple test." },
      { section: "Section 89", title: "Settlement of disputes outside the Court", description: "Statutory reference to mediation, conciliation, and Lok Adalat." }
    ],
    summary: "Comprehensive procedural code governing civil suits, execution, and injunctions.",
    demo: true,
  },
  {
    id: "stat-22",
    title: "Securities and Exchange Board of India Act, 1992 (SEBI Act)",
    actNumber: "Act No. 15 of 1992",
    year: 1992,
    enactedBy: "Parliament of India",
    domain: "Capital Markets & Securities",
    isModern: true,
    keySections: [
      { section: "Section 11B", title: "Power of Board to issue directions", description: "Plenary regulatory power to issue disgorgement and debarment orders." },
      { section: "Section 15HA", title: "Penalty for fraudulent and unfair trade practices", description: "Statutory monetary penalties for market manipulation." }
    ],
    summary: "Governs regulation of securities markets, insider trading prohibitions, and SAT appeals.",
    demo: true,
  }
];

// ============================================================================
// 22 FICTIONAL DEMONSTRATION JUDGMENTS (Explicitly marked Fictional Demo)
// ============================================================================
export const DEMO_JUDGMENTS: LegalSource[] = [
  {
    id: "jdg-01",
    title: "Apex Mercantile Infra Ltd. v. Union Territory of Indica & Anr. (Fictional Demo)",
    court: "Supreme Court of India (Fictional Bench)",
    year: 2025,
    date: "2025-02-14",
    citation: "2025 SCC OnLine SC 401 (Fictional)",
    legalArea: "Constitutional & Infrastructure Law",
    authorityLevel: "Supreme Court of India",
    verificationStatus: "VERIFIED",
    relevantSection: "Article 14, Specific Relief Act S. 20A",
    precedentStatus: "Good Law",
    summary: "Three-judge bench held that contractual blacklisting of infrastructure concessionaires without reasoned show-cause violates natural justice under Article 14.",
    demo: true,
  },
  {
    id: "jdg-02",
    title: "Virendra K. Singhania v. Directorate of Financial Enforcement (Fictional Demo)",
    court: "Supreme Court of India (Fictional Bench)",
    year: 2024,
    date: "2024-11-20",
    citation: "2024 SCC OnLine SC 892 (Fictional)",
    legalArea: "Criminal Law & Economic Offenses",
    authorityLevel: "Supreme Court of India",
    verificationStatus: "VERIFIED",
    relevantSection: "PMLA Section 45, BNSS Section 482",
    precedentStatus: "Good Law",
    summary: "Held that prolonged pre-trial incarceration exceeding three years without commencement of trial dilutes statutory twin conditions of bail under Article 21.",
    demo: true,
  },
  {
    id: "jdg-03",
    title: "Digital Rights Collective v. State of Fictional Pradesh (Fictional Demo)",
    court: "High Court of Delhi (Fictional Division Bench)",
    year: 2025,
    date: "2025-01-18",
    citation: "2025 DLT 341 (Fictional)",
    legalArea: "Cyber Law & Data Privacy",
    authorityLevel: "High Court",
    verificationStatus: "VERIFIED",
    relevantSection: "BSA 2023 Section 61, IT Act Section 79",
    precedentStatus: "Good Law",
    summary: "Electronic log integrity under BSA Section 61 requires automated hash verification; mere affidavit without chain of custody rejected.",
    demo: true,
  },
  {
    id: "jdg-04",
    title: "Indica Energy Holdings v. Global Maritime Freight Corp (Fictional Demo)",
    court: "Supreme Court of India (Fictional Bench)",
    year: 2024,
    date: "2024-08-30",
    citation: "2024 (5) Arb LR 112 (SC) (Fictional)",
    legalArea: "Commercial Arbitration",
    authorityLevel: "Supreme Court of India",
    verificationStatus: "VERIFIED",
    relevantSection: "Arbitration Act Section 34 & 37",
    precedentStatus: "Good Law",
    summary: "Courts hearing Section 34 and Section 37 petitions cannot rewrite arbitral contracts or substitute plausible contractual interpretations with court's own views.",
    demo: true,
  },
  {
    id: "jdg-05",
    title: "Bharat Solar Power Corp v. Southern Power Distribution Ltd. (Fictional Demo)",
    court: "High Court of Karnataka (Fictional Commercial Bench)",
    year: 2024,
    date: "2024-06-12",
    citation: "2024 Kar LJ 450 (Fictional)",
    legalArea: "Commercial Contracts & Renewable Energy",
    authorityLevel: "High Court",
    verificationStatus: "VERIFIED",
    relevantSection: "Specific Relief Act Section 10, Contract Act Section 73",
    precedentStatus: "Good Law",
    summary: "Power Purchase Agreements (PPAs) in renewable energy projects qualify for mandatory specific performance post-2018 amendment.",
    demo: true,
  },
  {
    id: "jdg-06",
    title: "State of Maharashtra v. Arvind G. Joshi (Fictional Demo)",
    court: "High Court of Bombay (Fictional Bench)",
    year: 2024,
    date: "2024-10-05",
    citation: "2024 Bom CR (Cri) 219 (Fictional)",
    legalArea: "Criminal Procedure (BNSS)",
    authorityLevel: "High Court",
    verificationStatus: "VERIFIED",
    relevantSection: "BNSS Section 35, BNSS Section 187",
    precedentStatus: "Good Law",
    summary: "Police failure to record contemporaneous reasons for arrest for offenses carrying punishment under 7 years renders detention unlawful under BNSS Section 35.",
    demo: true,
  },
  {
    id: "jdg-07",
    title: "Novartis Bio-Pharma Indica v. Dr. Reddy & Kumar Generics (Fictional Demo)",
    court: "High Court of Delhi (Fictional IP Division)",
    year: 2024,
    date: "2024-09-14",
    citation: "2024 (78) PTC 198 (Del) (Fictional)",
    legalArea: "Intellectual Property & Patents",
    authorityLevel: "High Court",
    verificationStatus: "PARTIALLY VERIFIED",
    relevantSection: "Patents Act Section 3(d)",
    precedentStatus: "Clarified",
    summary: "Clarified enhanced therapeutic efficacy evidentiary requirements in secondary polymorph patent applications.",
    demo: true,
  },
  {
    id: "jdg-08",
    title: "Kailash Logistics Pvt Ltd v. Pegasus Asset Reconstruction (Fictional Demo)",
    court: "National Company Law Appellate Tribunal (NCLAT - Fictional)",
    year: 2024,
    date: "2024-07-22",
    citation: "2024 Comp AT (Ins) 554 (Fictional)",
    legalArea: "Insolvency & Bankruptcy",
    authorityLevel: "Tribunal",
    verificationStatus: "VERIFIED",
    relevantSection: "IBC Section 9 & Section 14",
    precedentStatus: "Good Law",
    summary: "Pre-existing dispute under Section 9 cannot be a moonshine defense concocted after issuance of demand notice under Section 8.",
    demo: true,
  },
  {
    id: "jdg-09",
    title: "Pooja Hegde Builders v. RERA Regulatory Authority of Indica (Fictional Demo)",
    court: "High Court of Bombay (Fictional Division Bench)",
    year: 2024,
    date: "2024-04-10",
    citation: "2024 SCC OnLine Bom 114 (Fictional)",
    legalArea: "Real Estate Law",
    authorityLevel: "High Court",
    verificationStatus: "VERIFIED",
    relevantSection: "RERA Section 18",
    precedentStatus: "Good Law",
    summary: "Homebuyer's right to refund with statutory interest upon default in agreed possession date is absolute and unconditional.",
    demo: true,
  },
  {
    id: "jdg-10",
    title: "Standard Chartered Maritime v. Union of Indica (Fictional Demo)",
    court: "Supreme Court of India (Fictional Bench)",
    year: 2023,
    date: "2023-12-05",
    citation: "2023 (10) SCC 789 (Fictional)",
    legalArea: "Maritime & International Trade",
    authorityLevel: "Supreme Court of India",
    verificationStatus: "VERIFIED",
    relevantSection: "Admiralty Act Section 4",
    precedentStatus: "Good Law",
    summary: "Admiralty jurisdiction against sister ships affirmed where beneficial ownership is established by piercing the corporate veil.",
    demo: true,
  },
  {
    id: "jdg-11",
    title: "Kunal S. Deshmukh v. Serious Fraud Investigation Office (Fictional Demo)",
    court: "Supreme Court of India (Fictional Bench)",
    year: 2024,
    date: "2024-03-19",
    citation: "2024 (2) Crimes 108 (SC) (Fictional)",
    legalArea: "Corporate Fraud & Bail",
    authorityLevel: "Supreme Court of India",
    verificationStatus: "VERIFIED",
    relevantSection: "Companies Act S. 212(6), BNSS S. 482",
    precedentStatus: "Good Law",
    summary: "Economic offenses require serious judicial scrutiny, but mechanical rejection of bail when investigation is complete violates liberty.",
    demo: true,
  },
  {
    id: "jdg-12",
    title: "Horizon Fintech Ltd. v. Reserve Bank of Indica (Fictional Demo)",
    court: "Supreme Court of India (Fictional Constitutional Bench)",
    year: 2024,
    date: "2024-05-11",
    citation: "2024 (4) SCC 312 (Fictional)",
    legalArea: "Banking Regulation & Constitutional Law",
    authorityLevel: "Supreme Court of India",
    verificationStatus: "VERIFIED",
    relevantSection: "Article 19(1)(g), RBI Act S. 45JA",
    precedentStatus: "Good Law",
    summary: "Proportionality test applied to RBI circulars restricting digital lending applications; algorithmic due process principles articulated.",
    demo: true,
  },
  {
    id: "jdg-13",
    title: "Meenakshi Sundaram v. S. R. Educational Trust (Fictional Demo)",
    court: "High Court of Madras (Fictional Bench)",
    year: 2023,
    date: "2023-11-28",
    citation: "2023 (6) CTC 502 (Fictional)",
    legalArea: "Trusts & Educational Law",
    authorityLevel: "High Court",
    verificationStatus: "VERIFIED",
    relevantSection: "CPC Section 92",
    precedentStatus: "Good Law",
    summary: "Leave under Section 92 CPC is a condition precedent; suit instituted without prior leave is fundamentally incompetent.",
    demo: true,
  },
  {
    id: "jdg-14",
    title: "Apex Media Broadcasting v. Central Board of Film Certification (Fictional Demo)",
    court: "High Court of Delhi (Fictional Bench)",
    year: 2024,
    date: "2024-01-25",
    citation: "2024 DLT 112 (Fictional)",
    legalArea: "Freedom of Speech & Media Law",
    authorityLevel: "High Court",
    verificationStatus: "VERIFIED",
    relevantSection: "Article 19(1)(a), Cinematograph Act S. 5B",
    precedentStatus: "Good Law",
    summary: "Pre-censorship of documentary content cannot be justified on vague allegations of law and order without proximate threat.",
    demo: true,
  },
  {
    id: "jdg-15",
    title: "Star Telecommunications v. Dept of Telecommunications (Fictional Demo)",
    court: "Telecom Disputes Settlement Appellate Tribunal (TDSAT - Fictional)",
    year: 2023,
    date: "2023-09-17",
    citation: "2023 TDSAT 88 (Fictional)",
    legalArea: "Telecom & Administrative Law",
    authorityLevel: "Tribunal",
    verificationStatus: "VERIFIED",
    relevantSection: "Telegraph Act Section 4",
    precedentStatus: "Good Law",
    summary: "Levy of liquidated damages for non-operational spectrum tranches without demonstrable loss held arbitrary.",
    demo: true,
  },
  {
    id: "jdg-16",
    title: "Gautam R. Vora v. State of Gujarat (Fictional Demo)",
    court: "High Court of Gujarat (Fictional Bench)",
    year: 2024,
    date: "2024-08-08",
    citation: "2024 GLR 745 (Fictional)",
    legalArea: "Criminal Law (BNS Cheating)",
    authorityLevel: "High Court",
    verificationStatus: "VERIFIED",
    relevantSection: "BNS Section 318, BNSS Section 528 (Inherent Powers)",
    precedentStatus: "Good Law",
    summary: "Pure commercial breach of contract without dishonest inducement at inception cannot be criminalized under BNS Section 318.",
    demo: true,
  },
  {
    id: "jdg-17",
    title: "Zeta Chemical Industries v. State Pollution Control Board (Fictional Demo)",
    court: "National Green Tribunal (NGT Principal Bench - Fictional)",
    year: 2024,
    date: "2024-02-14",
    citation: "2024 NGT Reporter 33 (Fictional)",
    legalArea: "Environmental Law",
    authorityLevel: "Tribunal",
    verificationStatus: "VERIFIED",
    relevantSection: "Water Act S. 33A, NGT Act S. 15",
    precedentStatus: "Good Law",
    summary: "Precautionary principle and polluter pays principle invoked to sustain environmental compensation for untreated effluent discharge.",
    demo: true,
  },
  {
    id: "jdg-18",
    title: "Omkar Infratech v. Western Railway Administration (Fictional Demo)",
    court: "High Court of Bombay (Fictional Commercial Division)",
    year: 2024,
    date: "2024-07-02",
    citation: "2024 (3) Bom CR 612 (Fictional)",
    legalArea: "Arbitration & Government Tenders",
    authorityLevel: "High Court",
    verificationStatus: "VERIFIED",
    relevantSection: "Arbitration Act S. 11(6)",
    precedentStatus: "Good Law",
    summary: "Unilateral appointment clauses reserving power to Railway General Manager to pick sole arbitrator invalid under Section 12(5).",
    demo: true,
  },
  {
    id: "jdg-19",
    title: "Manjula S. Rao v. City Municipal Corporation (Fictional Demo)",
    court: "High Court of Karnataka (Fictional Bench)",
    year: 2024,
    date: "2024-04-29",
    citation: "2024 (2) Kar LJ 318 (Fictional)",
    legalArea: "Municipal & Property Law",
    authorityLevel: "High Court",
    verificationStatus: "PARTIALLY VERIFIED",
    relevantSection: "Article 300A, Karnataka Municipalities Act S. 187",
    precedentStatus: "Clarified",
    summary: "Demolition of unauthorized construction without prior statutory notice and opportunity to regularize held unconstitutional under Article 300A.",
    demo: true,
  },
  {
    id: "jdg-20",
    title: "Sunderlal & Sons v. Commissioner of Central GST (Fictional Demo)",
    court: "High Court of Delhi (Fictional Tax Division)",
    year: 2024,
    date: "2024-05-30",
    citation: "2024 (85) GSTL 14 (Del) (Fictional)",
    legalArea: "Indirect Taxation & GST",
    authorityLevel: "High Court",
    verificationStatus: "VERIFIED",
    relevantSection: "CGST Act Section 16(2)(c)",
    precedentStatus: "Good Law",
    summary: "Input Tax Credit (ITC) denial to bona fide purchaser for supplier default unconstitutional where transaction is genuine.",
    demo: true,
  },
  {
    id: "jdg-21",
    title: "Pinnacle Cloud Services v. Indian Revenue Service (Fictional Demo)",
    court: "Income Tax Appellate Tribunal (ITAT Delhi Bench - Fictional)",
    year: 2023,
    date: "2023-10-11",
    citation: "2023 ITAT Del 890 (Fictional)",
    legalArea: "Direct Tax & International Taxation",
    authorityLevel: "Tribunal",
    verificationStatus: "VERIFIED",
    relevantSection: "Income Tax Act S. 9(1)(vi), DTAA Article 12",
    precedentStatus: "Good Law",
    summary: "Payments for standard cloud hosting services (SaaS/IaaS) do not constitute royalties under DTAA.",
    demo: true,
  },
  {
    id: "jdg-22",
    title: "Kalyan Jewellers Syndicate v. Hallmark Standards Bureau (Fictional Demo)",
    court: "Supreme Court of India (Fictional Bench)",
    year: 2023,
    date: "2023-08-14",
    citation: "2023 (8) SCC 229 (Fictional)",
    legalArea: "Consumer & Standards Regulation",
    authorityLevel: "Supreme Court of India",
    verificationStatus: "VERIFIED",
    relevantSection: "BIS Act Section 14",
    precedentStatus: "Good Law",
    summary: "Mandatory hallmarking regulations upheld; reasonable regulatory restriction under Article 19(6) to protect consumer interest.",
    demo: true,
  }
];

// ============================================================================
// 22 FICTIONAL CASES FOR CASE MANAGEMENT
// ============================================================================
export const DEMO_CASES: CaseRecord[] = [
  {
    id: "case-01",
    organizationId: "org-demo-firm-01",
    title: "Apex Mercantile Infra v. UT of Indica (Arbitration Appeal)",
    caseNumber: "ARB.A. (COMM) 42/2025",
    court: "High Court of Delhi - Commercial Appellate Division",
    clientName: "Apex Mercantile Infrastructure Ltd.",
    practiceArea: "Commercial Arbitration",
    status: "Active",
    nextHearingDate: "2026-09-24",
    assignedLawyer: "Adv. Rajesh V. Nariman",
    assignedLawyerEmail: "demo.advocate@nyayaai.test",
    summary: "Appeal under Section 37 of the Arbitration Act against interim measure order refusing stay of invocation of performance bank guarantees.",
    createdAt: "2025-01-10T10:00:00Z",
    updatedAt: "2026-09-01T14:30:00Z",
    documentsCount: 6,
    demo: true,
    hearings: [
      {
        id: "hrg-01",
        caseId: "case-01",
        court: "Court No. 3, Delhi High Court",
        bench: "Hon'ble Mr. Justice R. K. Varma",
        hearingDate: "2026-09-24",
        purpose: "Final Arguments on Section 37 Appeal",
        status: "Scheduled"
      }
    ],
    events: [
      {
        id: "evt-01",
        caseId: "case-01",
        title: "Memorandum of Appeal Filed",
        type: "Filing",
        date: "2025-01-10",
        description: "Appeal filed under Section 37 with urgent application for interim stay.",
      },
      {
        id: "evt-02",
        caseId: "case-01",
        title: "Notice Issued to Respondent",
        type: "Notice",
        date: "2025-01-20",
        description: "Court issued notice returnable in three weeks with ad-interim protection.",
      },
      {
        id: "evt-03",
        caseId: "case-01",
        title: "Respondent Reply Filed",
        type: "Reply",
        date: "2025-03-05",
        description: "Respondent filed detailed reply affidavit disputing urgency.",
      }
    ]
  },
  {
    id: "case-02",
    organizationId: "org-demo-firm-01",
    title: "Indica Energy Holdings v. State Power Grid Corp",
    caseNumber: "CS (COMM) 189/2024",
    court: "High Court of Karnataka - Commercial Division",
    clientName: "Indica Energy Holdings Ltd.",
    practiceArea: "Energy & Contracts",
    status: "Active",
    nextHearingDate: "2026-10-04",
    assignedLawyer: "Adv. Rajesh V. Nariman",
    assignedLawyerEmail: "demo.advocate@nyayaai.test",
    summary: "Commercial suit seeking mandatory injunction and damages for wrongful termination of long-term solar power purchase contract.",
    createdAt: "2024-04-12T11:00:00Z",
    updatedAt: "2026-08-28T16:00:00Z",
    documentsCount: 9,
    demo: true,
    hearings: [
      {
        id: "hrg-02",
        caseId: "case-02",
        court: "Court Hall 7, Karnataka HC",
        bench: "Hon'ble Mrs. Justice Lalitha Rao",
        hearingDate: "2026-10-04",
        purpose: "Framing of Issues",
        status: "Scheduled"
      }
    ],
    events: [
      {
        id: "evt-04",
        caseId: "case-02",
        title: "Commercial Plaint Filed",
        type: "Filing",
        date: "2024-04-12",
        description: "Commercial suit valued at INR 48 Crores registered post Section 12A mediation waiver.",
      }
    ]
  },
  {
    id: "case-03",
    organizationId: "org-demo-firm-01",
    title: "Virendra K. Singhania v. SFIO (Regular Bail)",
    caseNumber: "BAIL APPLN. 1102/2025",
    court: "Supreme Court of India",
    clientName: "Virendra Kumar Singhania",
    practiceArea: "Criminal Law & Economic Offenses",
    status: "Active",
    nextHearingDate: "2026-09-18",
    assignedLawyer: "Adv. Rajesh V. Nariman",
    assignedLawyerEmail: "demo.advocate@nyayaai.test",
    summary: "Special Leave Petition seeking regular bail under Section 482 BNSS on grounds of parity and medical health.",
    createdAt: "2025-02-01T09:00:00Z",
    updatedAt: "2026-09-05T12:00:00Z",
    documentsCount: 14,
    demo: true,
    hearings: [
      {
        id: "hrg-03",
        caseId: "case-03",
        court: "Court 4, Supreme Court",
        bench: "Hon'ble Bench No. 4",
        hearingDate: "2026-09-18",
        purpose: "Arguments on Interim Medical Bail",
        status: "Scheduled"
      }
    ],
    events: [
      {
        id: "evt-05",
        caseId: "case-03",
        title: "SLP Filed",
        type: "Filing",
        date: "2025-02-01",
        description: "Petition filed challenging High Court order denying bail.",
      }
    ]
  },
  {
    id: "case-04",
    organizationId: "org-demo-firm-01",
    title: "Digital Rights Collective v. Union of Indica (Writ Petition)",
    caseNumber: "W.P.(C) 4901/2025",
    court: "High Court of Delhi - Constitutional Division",
    clientName: "Digital Rights Collective NGO",
    practiceArea: "Constitutional & Cyber Law",
    status: "Active",
    nextHearingDate: "2026-11-12",
    assignedLawyer: "Arjun S. Mehra",
    assignedLawyerEmail: "demo.associate@nyayaai.test",
    summary: "Public interest writ petition challenging statutory notifications mandating biometric client tracking without judicial oversight.",
    createdAt: "2025-03-01T14:00:00Z",
    updatedAt: "2026-08-15T11:00:00Z",
    documentsCount: 5,
    demo: true,
    hearings: [],
    events: []
  },
  {
    id: "case-05",
    organizationId: "org-demo-firm-01",
    title: "Pegasus Asset Reconstruction v. Kailash Logistics Ltd.",
    caseNumber: "CP (IB) 880/KB/2024",
    court: "NCLT Kolkata Bench",
    clientName: "Pegasus ARC Pvt Ltd",
    practiceArea: "Insolvency & Bankruptcy",
    status: "Pending",
    nextHearingDate: "2026-10-15",
    assignedLawyer: "Dr. Priyamvada Iyer",
    assignedLawyerEmail: "demo.admin@nyayaai.test",
    summary: "Section 7 IBC petition for insolvency commencement against corporate guarantor of INR 92 Crore credit facility.",
    createdAt: "2024-08-10T10:00:00Z",
    updatedAt: "2026-09-02T15:00:00Z",
    documentsCount: 11,
    demo: true,
    hearings: [],
    events: []
  },
  {
    id: "case-06",
    organizationId: "org-demo-firm-01",
    title: "Novartis Bio-Pharma v. Sun & Kumar Lifesciences",
    caseNumber: "CS (COMM) 310/2024",
    court: "High Court of Delhi - IP Division",
    clientName: "Novartis Bio-Pharma Indica",
    practiceArea: "Intellectual Property",
    status: "Active",
    nextHearingDate: "2026-09-29",
    assignedLawyer: "Arjun S. Mehra",
    assignedLawyerEmail: "demo.associate@nyayaai.test",
    summary: "Patent infringement action concerning crystalline formulation of cardiovascular inhibitor compound.",
    createdAt: "2024-05-18T16:00:00Z",
    updatedAt: "2026-08-20T10:00:00Z",
    documentsCount: 8,
    demo: true,
    hearings: [],
    events: []
  },
  {
    id: "case-07",
    organizationId: "org-demo-firm-01",
    title: "Horizon Fintech v. Payment Regulatory Authority",
    caseNumber: "W.P.(C) 6780/2024",
    court: "High Court of Bombay",
    clientName: "Horizon Fintech Technologies Pvt Ltd",
    practiceArea: "Fintech & Banking Regulation",
    status: "Active",
    nextHearingDate: "2026-10-22",
    assignedLawyer: "Adv. Rajesh V. Nariman",
    assignedLawyerEmail: "demo.advocate@nyayaai.test",
    summary: "Writ challenging suspension of payment aggregator license based on algorithmic risk score discrepancy.",
    createdAt: "2024-06-25T11:00:00Z",
    updatedAt: "2026-09-04T09:00:00Z",
    documentsCount: 4,
    demo: true,
    hearings: [],
    events: []
  },
  {
    id: "case-08",
    organizationId: "org-demo-firm-01",
    title: "Pooja Hegde Homebuyers Association v. Skyward Developers",
    caseNumber: "RERA/COMP/2024/0912",
    court: "MahaRERA Mumbai Bench",
    clientName: "Skyward Horizon Allottees Association",
    practiceArea: "Real Estate & Homebuyers",
    status: "Active",
    nextHearingDate: "2026-09-30",
    assignedLawyer: "Dr. Priyamvada Iyer",
    assignedLawyerEmail: "demo.admin@nyayaai.test",
    summary: "Group complaint under Section 18 RERA demanding refund of INR 32 Crores with interest for delayed possession.",
    createdAt: "2024-09-02T13:00:00Z",
    updatedAt: "2026-08-30T17:00:00Z",
    documentsCount: 7,
    demo: true,
    hearings: [],
    events: []
  },
  {
    id: "case-09",
    organizationId: "org-demo-firm-01",
    title: "Zeta Chemical Industries v. Central Pollution Control Board",
    caseNumber: "OA 412/2024/PB",
    court: "National Green Tribunal - Principal Bench, New Delhi",
    clientName: "Zeta Chemical Industries",
    practiceArea: "Environmental Litigation",
    status: "Pending",
    nextHearingDate: "2026-11-05",
    assignedLawyer: "Adv. Rajesh V. Nariman",
    assignedLawyerEmail: "demo.advocate@nyayaai.test",
    summary: "Challenge to closure order and INR 5 Crore environmental compensation levy for alleged industrial discharge.",
    createdAt: "2024-07-15T09:00:00Z",
    updatedAt: "2026-08-10T14:00:00Z",
    documentsCount: 12,
    demo: true,
    hearings: [],
    events: []
  },
  {
    id: "case-10",
    organizationId: "org-demo-firm-01",
    title: "Sunderlal & Sons Jewellers v. Union of Indica (GST Writ)",
    caseNumber: "W.P.(C) 1205/2024",
    court: "High Court of Delhi - Tax Division",
    clientName: "Sunderlal & Sons Ltd.",
    practiceArea: "Taxation & GST",
    status: "Closed",
    nextHearingDate: undefined,
    assignedLawyer: "Dr. Priyamvada Iyer",
    assignedLawyerEmail: "demo.admin@nyayaai.test",
    summary: "Writ challenging retrospective cancellation of GST registration and blocking of input tax credit.",
    createdAt: "2024-02-10T10:00:00Z",
    updatedAt: "2024-12-15T18:00:00Z",
    documentsCount: 6,
    demo: true,
    hearings: [],
    events: []
  },
  {
    id: "case-11",
    organizationId: "org-demo-firm-01",
    title: "State of Maharashtra v. Rohan Deshpande (Anticipatory Bail)",
    caseNumber: "ABA 512/2025",
    court: "High Court of Bombay",
    clientName: "Rohan Deshpande",
    practiceArea: "Criminal Law (BNS/BNSS)",
    status: "Active",
    nextHearingDate: "2026-09-15",
    assignedLawyer: "Adv. Rajesh V. Nariman",
    assignedLawyerEmail: "demo.advocate@nyayaai.test",
    summary: "Anticipatory bail under BNSS Section 482 in alleged financial misappropriation under BNS Section 316/318.",
    createdAt: "2025-08-01T15:00:00Z",
    updatedAt: "2026-09-04T11:00:00Z",
    documentsCount: 3,
    demo: true,
    hearings: [],
    events: []
  },
  {
    id: "case-12",
    organizationId: "org-demo-firm-01",
    title: "Meenakshi Tech Solutions v. Karnataka Power Corp",
    caseNumber: "ARB (COMM) 91/2024",
    court: "Commercial Court, Bengaluru",
    clientName: "Meenakshi Tech Solutions",
    practiceArea: "Commercial Arbitration",
    status: "Active",
    nextHearingDate: "2026-10-18",
    assignedLawyer: "Arjun S. Mehra",
    assignedLawyerEmail: "demo.associate@nyayaai.test",
    summary: "Section 9 application for injunction against unilateral encashment of advance bank guarantees.",
    createdAt: "2024-10-15T10:00:00Z",
    updatedAt: "2026-08-25T16:00:00Z",
    documentsCount: 5,
    demo: true,
    hearings: [],
    events: []
  },
  {
    id: "case-13",
    organizationId: "org-demo-firm-01",
    title: "Pinnacle Cloud v. Deputy Commissioner of Income Tax",
    caseNumber: "ITA 1450/DEL/2024",
    court: "ITAT New Delhi",
    clientName: "Pinnacle Cloud Services Inc.",
    practiceArea: "Direct Tax & Cross-Border",
    status: "Active",
    nextHearingDate: "2026-11-20",
    assignedLawyer: "Dr. Priyamvada Iyer",
    assignedLawyerEmail: "demo.admin@nyayaai.test",
    summary: "Cross-border tax appeal asserting SaaS subscription fees do not constitute royalty under Indo-US DTAA.",
    createdAt: "2024-11-01T12:00:00Z",
    updatedAt: "2026-08-18T10:00:00Z",
    documentsCount: 8,
    demo: true,
    hearings: [],
    events: []
  },
  {
    id: "case-14",
    organizationId: "org-demo-firm-01",
    title: "Kalyan Mercantile Bank v. Somnath Steels Pvt Ltd",
    caseNumber: "OA 310/2024",
    court: "Debts Recovery Tribunal (DRT-II Mumbai)",
    clientName: "Kalyan Mercantile Co-op Bank",
    practiceArea: "Banking Recovery & SARFAESI",
    status: "Pending",
    nextHearingDate: "2026-10-29",
    assignedLawyer: "Adv. Rajesh V. Nariman",
    assignedLawyerEmail: "demo.advocate@nyayaai.test",
    summary: "Original Application for recovery of INR 18.5 Crores together with mortgage enforcement under SARFAESI Act.",
    createdAt: "2024-07-20T11:00:00Z",
    updatedAt: "2026-08-12T14:00:00Z",
    documentsCount: 10,
    demo: true,
    hearings: [],
    events: []
  },
  {
    id: "case-15",
    organizationId: "org-demo-firm-01",
    title: "Aura Luxury Retail v. Fashion Forward E-Commerce",
    caseNumber: "CS (COMM) 540/2024",
    court: "High Court of Delhi - Commercial Division",
    clientName: "Aura Luxury Retail LLC",
    practiceArea: "Trademark & Passing Off",
    status: "Active",
    nextHearingDate: "2026-10-08",
    assignedLawyer: "Arjun S. Mehra",
    assignedLawyerEmail: "demo.associate@nyayaai.test",
    summary: "Injunction against sale of counterfeit luxury designer apparel on online marketplace platform.",
    createdAt: "2024-09-12T16:00:00Z",
    updatedAt: "2026-09-03T11:00:00Z",
    documentsCount: 6,
    demo: true,
    hearings: [],
    events: []
  },
  {
    id: "case-16",
    organizationId: "org-demo-firm-01",
    title: "Gautam R. Vora v. State of Gujarat (Quashing Petition)",
    caseNumber: "CR.MA 8920/2024",
    court: "High Court of Gujarat",
    clientName: "Gautam R. Vora",
    practiceArea: "Criminal Quashing (BNSS 528)",
    status: "Pending",
    nextHearingDate: "2026-10-14",
    assignedLawyer: "Adv. Rajesh V. Nariman",
    assignedLawyerEmail: "demo.advocate@nyayaai.test",
    summary: "Petition under Section 528 BNSS seeking quashing of criminal complaint arising purely out of contractual sale transaction.",
    createdAt: "2024-08-22T09:00:00Z",
    updatedAt: "2026-08-31T15:00:00Z",
    documentsCount: 4,
    demo: true,
    hearings: [],
    events: []
  },
  {
    id: "case-17",
    organizationId: "org-demo-firm-01",
    title: "Indica Ports & Terminals v. Union of Indica (Tender Dispute)",
    caseNumber: "W.P.(C) 8112/2025",
    court: "High Court of Bombay",
    clientName: "Indica Ports & Terminals Ltd.",
    practiceArea: "Government Contracts & Tenders",
    status: "Active",
    nextHearingDate: "2026-11-03",
    assignedLawyer: "Dr. Priyamvada Iyer",
    assignedLawyerEmail: "demo.admin@nyayaai.test",
    summary: "Writ challenging arbitrary disqualification of technical bid for development of automated container terminal.",
    createdAt: "2025-05-10T10:00:00Z",
    updatedAt: "2026-09-02T13:00:00Z",
    documentsCount: 9,
    demo: true,
    hearings: [],
    events: []
  },
  {
    id: "case-18",
    organizationId: "org-demo-firm-01",
    title: "Pradeep K. Bansal v. New Horizon Real Estate (RERA Appeal)",
    caseNumber: "REAT APP 44/2025",
    court: "Maharashtra Real Estate Appellate Tribunal",
    clientName: "Pradeep K. Bansal",
    practiceArea: "Real Estate & Consumer",
    status: "Active",
    nextHearingDate: "2026-10-20",
    assignedLawyer: "Dr. Priyamvada Iyer",
    assignedLawyerEmail: "demo.admin@nyayaai.test",
    summary: "Statutory appeal against RERA order reducing delay compensation awarded to homebuyer.",
    createdAt: "2025-04-18T14:00:00Z",
    updatedAt: "2026-08-20T17:00:00Z",
    documentsCount: 3,
    demo: true,
    hearings: [],
    events: []
  },
  {
    id: "case-19",
    organizationId: "org-demo-firm-01",
    title: "Star Telecommunications v. DoT (TDSAT Appeal)",
    caseNumber: "PETITION 32/2024",
    court: "TDSAT New Delhi",
    clientName: "Star Telecommunications India",
    practiceArea: "Telecom & Administrative",
    status: "Pending",
    nextHearingDate: "2026-11-25",
    assignedLawyer: "Arjun S. Mehra",
    assignedLawyerEmail: "demo.associate@nyayaai.test",
    summary: "Appeal against demand notice for adjusted gross revenue (AGR) calculation on non-telecom income streams.",
    createdAt: "2024-03-20T11:00:00Z",
    updatedAt: "2026-08-14T10:00:00Z",
    documentsCount: 8,
    demo: true,
    hearings: [],
    events: []
  },
  {
    id: "case-20",
    organizationId: "org-demo-firm-01",
    title: "Omkar Infratech v. Western Railway (Section 11 Arbitration)",
    caseNumber: "ARB.P. 510/2024",
    court: "High Court of Bombay",
    clientName: "Omkar Infratech Pvt Ltd",
    practiceArea: "Commercial Arbitration",
    status: "Closed",
    nextHearingDate: undefined,
    assignedLawyer: "Adv. Rajesh V. Nariman",
    assignedLawyerEmail: "demo.advocate@nyayaai.test",
    summary: "Application for independent arbitrator appointment following invalidation of unilateral panel nomination clause.",
    createdAt: "2024-05-15T15:00:00Z",
    updatedAt: "2024-11-28T16:00:00Z",
    documentsCount: 4,
    demo: true,
    hearings: [],
    events: []
  },
  {
    id: "case-21",
    organizationId: "org-demo-firm-01",
    title: "Securities Board v. Prime Horizon Capital (SAT Appeal)",
    caseNumber: "APPEAL NO. 219/2025",
    court: "Securities Appellate Tribunal (SAT Mumbai)",
    clientName: "Prime Horizon Capital Advisors",
    practiceArea: "Securities & Capital Markets",
    status: "Active",
    nextHearingDate: "2026-10-12",
    assignedLawyer: "Dr. Priyamvada Iyer",
    assignedLawyerEmail: "demo.admin@nyayaai.test",
    summary: "Appeal against SEBI order imposing penalty for alleged non-disclosure of algorithmic trading parameters.",
    createdAt: "2025-06-05T12:00:00Z",
    updatedAt: "2026-09-01T15:00:00Z",
    documentsCount: 7,
    demo: true,
    hearings: [],
    events: []
  },
  {
    id: "case-22",
    organizationId: "org-demo-firm-01",
    title: "Lalita S. Deshmukh v. Rajeshwar Developers (Specific Performance)",
    caseNumber: "CIVIL SUIT 112/2024",
    court: "City Civil Court, Hyderabad",
    clientName: "Lalita S. Deshmukh",
    practiceArea: "Real Estate & Contracts",
    status: "Active",
    nextHearingDate: "2026-10-19",
    assignedLawyer: "Arjun S. Mehra",
    assignedLawyerEmail: "demo.associate@nyayaai.test",
    summary: "Suit for specific performance of registered agreement to sell prime commercial plot post-2018 amendment.",
    createdAt: "2024-06-18T10:00:00Z",
    updatedAt: "2026-08-26T12:00:00Z",
    documentsCount: 5,
    demo: true,
    hearings: [],
    events: []
  }
];

// ============================================================================
// 10 FICTIONAL DOCUMENTS FOR DOCUMENT MANAGEMENT & AI ANALYSIS
// ============================================================================
export const DEMO_DOCUMENTS: DocumentRecord[] = [
  {
    id: "doc-01",
    organizationId: "org-demo-firm-01",
    caseId: "case-01",
    caseTitle: "Apex Mercantile Infra v. UT of Indica",
    name: "Commercial_Concession_Agreement_2022.pdf",
    fileType: "pdf",
    sizeBytes: 3450000,
    pageCount: 68,
    uploadedAt: "2025-01-10T10:30:00Z",
    status: "Analyzed",
    aiStatus: "Completed",
    summary: "Master Concession Agreement for construction and operation of toll expressway. Features disputed Clause 34.2 (unilateral termination) and Clause 38 (arbitration clause).",
    extractedProvisions: ["Clause 14.1 (Force Majeure)", "Clause 34.2 (Default and Termination)", "Clause 38.1 (Arbitration Seat at New Delhi)"],
    identifiedRisks: [
      "Clause 34.2 permits 15-day termination without cure period; likely vulnerable under Article 14 fairness doctrine.",
      "Clause 38.3 designates unilateral arbitrator nomination by grantor; vulnerable under Section 12(5) Arbitration Act."
    ],
    keyClauses: [
      {
        title: "Dispute Resolution",
        excerpt: "All disputes arising out of or in connection with this agreement shall be referred to arbitration seated exclusively in New Delhi under the Arbitration and Conciliation Act, 1996.",
        significance: "Crucial for establishing jurisdiction in Delhi High Court under Section 37."
      }
    ],
    demo: true,
  },
  {
    id: "doc-02",
    organizationId: "org-demo-firm-01",
    caseId: "case-03",
    caseTitle: "Virendra K. Singhania v. SFIO",
    name: "SFIO_Investigation_Report_Chargesheet.pdf",
    fileType: "pdf",
    sizeBytes: 8200000,
    pageCount: 142,
    uploadedAt: "2025-02-02T11:15:00Z",
    status: "Analyzed",
    aiStatus: "Completed",
    summary: "Investigation report alleging siphoning of corporate funds under Section 447 Companies Act and money laundering under PMLA Section 3.",
    extractedProvisions: ["Companies Act Section 212(6)", "PMLA Section 45", "BNSS Section 482"],
    identifiedRisks: [
      "Rigid twin conditions applicable under Section 212(6) unless parity or Article 21 constitutional delay demonstrated."
    ],
    demo: true,
  },
  {
    id: "doc-03",
    organizationId: "org-demo-firm-01",
    caseId: "case-02",
    caseTitle: "Indica Energy Holdings v. State Power Grid Corp",
    name: "Solar_PPA_25Year_Executed.docx",
    fileType: "docx",
    sizeBytes: 1250000,
    pageCount: 44,
    uploadedAt: "2024-04-14T09:00:00Z",
    status: "Analyzed",
    aiStatus: "Completed",
    summary: "Executed 25-year Power Purchase Agreement at tariff rate of INR 2.82/kWh. Governed by Specific Relief Act Section 10.",
    extractedProvisions: ["Section 10 Specific Relief Act", "Clause 19 (Remedies for Breach)"],
    identifiedRisks: ["Liquidated damages cap may limit compensation claims unless specific performance is prioritized."],
    demo: true,
  },
  {
    id: "doc-04",
    organizationId: "org-demo-firm-01",
    caseId: "case-04",
    caseTitle: "Digital Rights Collective v. Union of Indica",
    name: "Draft_Public_Interest_Writ_Petition.pdf",
    fileType: "pdf",
    sizeBytes: 1850000,
    pageCount: 38,
    uploadedAt: "2025-03-02T14:30:00Z",
    status: "Analyzed",
    aiStatus: "Completed",
    summary: "Article 226 writ petition challenging algorithmic surveillance directives under Articles 14, 19, and 21 (Puttaswamy privacy mandate).",
    extractedProvisions: ["Articles 14, 19(1)(a), 21", "DPDP Act 2023 Section 8"],
    identifiedRisks: ["Locus standi must be firmly established via affidavit of petitioner collective."],
    demo: true,
  },
  {
    id: "doc-05",
    organizationId: "org-demo-firm-01",
    caseId: "case-05",
    caseTitle: "Pegasus Asset Reconstruction v. Kailash Logistics Ltd.",
    name: "Deed_of_Corporate_Guarantee_Loan_Agreements.pdf",
    fileType: "pdf",
    sizeBytes: 4120000,
    pageCount: 52,
    uploadedAt: "2024-08-11T12:00:00Z",
    status: "Analyzed",
    aiStatus: "Completed",
    summary: "Irrevocable continuing corporate guarantee backing INR 92 Crore credit facility. Enforceable under Section 7 IBC independently of principal debtor.",
    extractedProvisions: ["IBC Section 7", "Contract Act Section 128 (Co-extensive liability)"],
    identifiedRisks: ["Corporate guarantor stamping adequacy under State Stamp Act should be verified."],
    demo: true,
  },
  {
    id: "doc-06",
    organizationId: "org-demo-firm-01",
    caseId: "case-06",
    caseTitle: "Novartis Bio-Pharma v. Sun & Kumar Lifesciences",
    name: "Patent_Specification_IN_298412.pdf",
    fileType: "pdf",
    sizeBytes: 5200000,
    pageCount: 84,
    uploadedAt: "2024-05-20T10:00:00Z",
    status: "Analyzed",
    aiStatus: "Completed",
    summary: "Complete patent specification claiming crystalline form of kinase inhibitor with comparative pharmacokinetics data.",
    extractedProvisions: ["Patents Act Section 3(d)", "Patents Act Section 48"],
    identifiedRisks: ["Defendant has filed pre-grant opposition alleging lack of enhanced therapeutic efficacy."],
    demo: true,
  },
  {
    id: "doc-07",
    organizationId: "org-demo-firm-01",
    caseId: "case-07",
    caseTitle: "Horizon Fintech v. Payment Regulatory Authority",
    name: "Show_Cause_Notice_Suspension_License.pdf",
    fileType: "pdf",
    sizeBytes: 980000,
    pageCount: 16,
    uploadedAt: "2024-06-26T15:00:00Z",
    status: "Analyzed",
    aiStatus: "Completed",
    summary: "Regulatory show-cause notice alleging cross-border merchant payout settlement non-compliances.",
    extractedProvisions: ["Payment and Settlement Systems Act S. 8"],
    identifiedRisks: ["Failure to submit merchant audit reports within 15 days triggers statutory cancellation."],
    demo: true,
  },
  {
    id: "doc-08",
    organizationId: "org-demo-firm-01",
    caseId: "case-08",
    caseTitle: "Pooja Hegde Homebuyers Association v. Skyward Developers",
    name: "Allotment_Letters_and_Delay_Notices.pdf",
    fileType: "pdf",
    sizeBytes: 2900000,
    pageCount: 62,
    uploadedAt: "2024-09-04T11:00:00Z",
    status: "Analyzed",
    aiStatus: "Completed",
    summary: "Consolidated allotment agreements establishing possession commitment of December 2022. Delay of 22 months documented.",
    extractedProvisions: ["RERA Section 18", "MahaRERA General Regulations"],
    identifiedRisks: ["Force majeure defense invoked by promoter citing municipal clearance delays; held non-viable in law."],
    demo: true,
  },
  {
    id: "doc-09",
    organizationId: "org-demo-firm-01",
    caseId: "case-09",
    caseTitle: "Zeta Chemical Industries v. CPCB",
    name: "Environmental_Audit_Report_Effluent_Parameters.pdf",
    fileType: "pdf",
    sizeBytes: 3750000,
    pageCount: 46,
    uploadedAt: "2024-07-16T13:30:00Z",
    status: "Analyzed",
    aiStatus: "Completed",
    summary: "Third-party laboratory analysis showing biochemical oxygen demand (BOD) and chemical oxygen demand (COD) levels compliant with CPCB standards.",
    extractedProvisions: ["Environment Protection Act S. 5", "Water Act S. 33A"],
    identifiedRisks: ["Chain of sample custody disputed by state pollution control board."],
    demo: true,
  },
  {
    id: "doc-10",
    organizationId: "org-demo-firm-01",
    caseId: "case-11",
    caseTitle: "State of Maharashtra v. Rohan Deshpande",
    name: "FIR_No_104_2025_Cyber_Police_Station.pdf",
    fileType: "pdf",
    sizeBytes: 1100000,
    pageCount: 12,
    uploadedAt: "2025-08-02T10:00:00Z",
    status: "Analyzed",
    aiStatus: "Completed",
    summary: "First Information Report lodged under BNS Sections 316 and 318 alleging cryptocurrency investment fraud.",
    extractedProvisions: ["BNS Section 316 (Breach of Trust)", "BNS Section 318 (Cheating)", "BNSS Section 482 (Anticipatory Bail)"],
    identifiedRisks: ["Accused has clean antecedents; custodial interrogation not required as all records are digital and seized."],
    demo: true,
  }
];

// ============================================================================
// 10 FICTIONAL RESEARCH SESSIONS
// ============================================================================
export const DEMO_RESEARCH_SESSIONS: ResearchSession[] = [
  {
    id: "res-01",
    organizationId: "org-demo-firm-01",
    userId: "user-advocate-01",
    title: "Bail criteria for economic offenses under BNSS 2023 vs CrPC",
    previewQuery: "Analyze legal standards and judicial discretion for anticipatory and regular bail in high-value economic offenses under BNSS Section 480 and 482.",
    legalArea: "Criminal Law (BNSS/BNS)",
    createdAt: "2026-09-02T10:30:00Z",
    updatedAt: "2026-09-02T10:35:00Z",
    isSaved: true,
    sources: [DEMO_JUDGMENTS[1], DEMO_JUDGMENTS[5], DEMO_JUDGMENTS[10]],
    messages: [
      {
        id: "msg-01",
        sessionId: "res-01",
        sender: "user",
        content: "Analyze the legal standards and judicial discretion for granting bail in complex economic offenses under the Bharatiya Nagarik Suraksha Sanhita, 2023 (BNSS) as compared to the erstwhile Code of Criminal Procedure, 1973.",
        timestamp: "2026-09-02T10:30:00Z"
      },
      {
        id: "msg-02",
        sessionId: "res-01",
        sender: "ai",
        content: "The transition from the Code of Criminal Procedure, 1973 (CrPC) to the Bharatiya Nagarik Suraksha Sanhita, 2023 (BNSS) reinforces foundational constitutional protections under Article 21 while modernizing procedural timelines. Under BNSS Section 480 (formerly CrPC S. 437) and BNSS Section 482 (formerly CrPC S. 439), bail in economic offenses continues to balance magnitude of financial loss with liberty guarantees against punitive pre-trial detention.",
        timestamp: "2026-09-02T10:30:15Z",
        stagesCompleted: [
          "Understanding legal question",
          "Identifying jurisdiction (Supreme Court & High Courts)",
          "Identifying legal domain (BNSS Procedural & Special Laws)",
          "Searching statutes (BNSS 2023, PMLA 2002)",
          "Searching authorities (Fictional Court Decisions)",
          "Comparing authorities & verifying citations",
          "Preparing response"
        ],
        structuredResponse: {
          legalIssue: "Whether high financial valuation in economic offenses automatically disentitles an accused to regular or anticipatory bail under BNSS Section 480 and 482 where investigation is substantially documented.",
          shortAnswer: "No. While economic offenses are viewed seriously, judicial discretion under BNSS Section 480/482 requires demonstration of flight risk, witness tampering, or destruction of evidence. Prolonged pre-trial detention cannot substitute for trial.",
          applicableLaw: [
            "Bharatiya Nagarik Suraksha Sanhita, 2023 (BNSS) Sections 35, 187, 480, 482",
            "Constitution of India, Article 21 (Personal Liberty)",
            "Prevention of Money Laundering Act, 2002, Section 45"
          ],
          authorities: [
            "Virendra K. Singhania v. Directorate of Financial Enforcement (2024 SCC OnLine SC 892 - Fictional)",
            "Kunal S. Deshmukh v. Serious Fraud Investigation Office (2024 (2) Crimes 108 SC - Fictional)",
            "State of Maharashtra v. Arvind G. Joshi (2024 Bom CR (Cri) 219 - Fictional)"
          ],
          analysis: "Under BNSS 2023, the procedural framework for custody under Section 187 requires objective justification. The Supreme Court in Virendra K. Singhania (Fictional) reaffirmed that even under special statutes with twin conditions, the constitutional guarantee of speedy trial under Article 21 serves as a paramount overriding principle. Where thousands of documents have been seized and documentary evidence is within police custody, pre-trial detention ceases to serve an investigative purpose and borders on punitive incarceration.",
          supportingAuthorities: [
            "Virendra K. Singhania v. Directorate of Financial Enforcement (Fictional Demo)",
            "Kunal S. Deshmukh v. SFIO (Fictional Demo)"
          ],
          contraryAuthorities: [
            "Special Enforcement Directorate v. Capital Holdings (Fictional) holding that grave economic loss to the public exchequer warrants heightened scrutiny."
          ],
          practicalConsiderations: [
            "Ensure immediate surrender of passport and readiness to furnish substantial local sureties.",
            "Establish on affidavit that all bank accounts, accounting servers, and records have been formally seized by investigating agencies.",
            "Demonstrate clean past criminal record and lack of any overseas residence permits."
          ],
          unresolvedQuestions: [
            "Judicial consensus is still emerging on whether BNSS Section 187 permits split police custody beyond the initial 15-day window in special economic offense tribunals."
          ],
          confidence: "high",
          verificationStatus: "VERIFIED",
          sources: [DEMO_JUDGMENTS[1], DEMO_JUDGMENTS[5], DEMO_JUDGMENTS[10]],
          disclaimer: "NyayaAI provides AI-assisted legal research, analysis and drafting support. It is not a substitute for professional legal judgment. Always verify statutes, amendments, judgments, procedural requirements and citations against authoritative original sources before relying on them. [FICTIONAL DEMONSTRATION DATA]"
        }
      }
    ]
  },
  {
    id: "res-02",
    organizationId: "org-demo-firm-01",
    userId: "user-advocate-01",
    title: "Enforceability of unilateral arbitrator appointment clauses post-2015 amendment",
    previewQuery: "Review Supreme Court jurisprudence on unilateral appointment of sole arbitrators by public sector undertakings.",
    legalArea: "Commercial Arbitration",
    createdAt: "2026-08-28T14:10:00Z",
    updatedAt: "2026-08-28T14:15:00Z",
    isSaved: true,
    sources: [DEMO_JUDGMENTS[3], DEMO_JUDGMENTS[17]],
    messages: [
      {
        id: "msg-03",
        sessionId: "res-02",
        sender: "user",
        content: "Is a clause empowering a Government PSU or Railway General Manager to appoint a sole arbitrator or select from a narrow panel of retired employees valid under Section 12(5) of the Arbitration Act?",
        timestamp: "2026-08-28T14:10:00Z"
      },
      {
        id: "msg-04",
        sessionId: "res-02",
        sender: "ai",
        content: "Unilateral arbitrator appointments and narrow captive panels curated by one party are legally invalid under Section 12(5) read with the Seventh Schedule of the Arbitration and Conciliation Act, 1996.",
        timestamp: "2026-08-28T14:10:20Z",
        structuredResponse: {
          legalIssue: "Validity of unilateral sole arbitrator appointment clauses in public procurement contracts post-Perkins and TRF jurisprudence.",
          shortAnswer: "Wholly invalid. A party ineligible to act as an arbitrator under Section 12(5) cannot unilaterally nominate an arbitrator.",
          applicableLaw: [
            "Arbitration and Conciliation Act, 1996, Section 11(6), Section 12(5), Seventh Schedule"
          ],
          authorities: [
            "Omkar Infratech v. Western Railway Administration (2024 (3) Bom CR 612 - Fictional)",
            "Indica Energy Holdings v. Global Maritime (2024 (5) Arb LR 112 SC - Fictional)"
          ],
          analysis: "Natural justice and statutory equality of parties demand that neither party can unilaterally control the composition of the arbitral tribunal. Narrow institutional panels comprising ex-employees fail the test of institutional independence.",
          supportingAuthorities: ["Omkar Infratech v. Western Railway (Fictional Demo)"],
          contraryAuthorities: [],
          practicalConsiderations: [
            "Directly file Section 11(6) petition before the High Court seeking appointment of an independent former Judge."
          ],
          unresolvedQuestions: ["Applicability of broad non-exclusive panels maintained by recognized arbitral institutions."],
          confidence: "high",
          verificationStatus: "VERIFIED",
          sources: [DEMO_JUDGMENTS[3], DEMO_JUDGMENTS[17]],
          disclaimer: "NyayaAI provides AI-assisted legal research. All authorities are Fictional Demonstration Data."
        }
      }
    ]
  },
  {
    id: "res-03",
    organizationId: "org-demo-firm-01",
    userId: "user-associate-01",
    title: "Electronic evidence certification under Section 61 Bharatiya Sakshya Adhiniyam, 2023",
    previewQuery: "How does BSA 2023 Section 61/63 alter the certificate requirements previously governed by Section 65B of the Indian Evidence Act?",
    legalArea: "Law of Evidence (BSA 2023)",
    createdAt: "2026-08-20T16:00:00Z",
    updatedAt: "2026-08-20T16:05:00Z",
    isSaved: false,
    sources: [DEMO_JUDGMENTS[2]],
    messages: []
  },
  {
    id: "res-04",
    organizationId: "org-demo-firm-01",
    userId: "user-admin-01",
    title: "Pre-institution mediation under Section 12A Commercial Courts Act: Is it mandatory?",
    previewQuery: "Examine whether Section 12A Commercial Courts Act 2015 is strictly mandatory or if urgent interim relief excuses pre-litigation mediation.",
    legalArea: "Commercial Litigation",
    createdAt: "2026-08-15T11:00:00Z",
    updatedAt: "2026-08-15T11:05:00Z",
    isSaved: true,
    sources: [DEMO_JUDGMENTS[4], DEMO_JUDGMENTS[0]],
    messages: []
  },
  {
    id: "res-05",
    organizationId: "org-demo-firm-01",
    userId: "user-advocate-01",
    title: "Clean Slate Doctrine under Section 31 IBC: Extinguishment of past statutory dues",
    previewQuery: "Impact of resolution plan approval by NCLT on pending tax and municipal penalties.",
    legalArea: "Insolvency & Bankruptcy",
    createdAt: "2026-08-10T09:00:00Z",
    updatedAt: "2026-08-10T09:04:00Z",
    isSaved: false,
    sources: [DEMO_JUDGMENTS[7]],
    messages: []
  },
  {
    id: "res-06",
    organizationId: "org-demo-firm-01",
    userId: "user-associate-01",
    title: "Intermediary Safe Harbor under Section 79 IT Act post-2023 Digital Media Rules",
    previewQuery: "Due diligence requirements for digital social platforms to maintain statutory safe harbor.",
    legalArea: "Cyber Law & IT Act",
    createdAt: "2026-08-01T15:00:00Z",
    updatedAt: "2026-08-01T15:04:00Z",
    isSaved: false,
    sources: [DEMO_JUDGMENTS[2]],
    messages: []
  },
  {
    id: "res-07",
    organizationId: "org-demo-firm-01",
    userId: "user-advocate-01",
    title: "Quashing of FIR for commercial breach under BNSS Section 528 vs BNS 318",
    previewQuery: "Distinguishing civil breach of contract from criminal cheating at the threshold stage.",
    legalArea: "Criminal Law & Quashing",
    createdAt: "2026-07-25T12:00:00Z",
    updatedAt: "2026-07-25T12:05:00Z",
    isSaved: true,
    sources: [DEMO_JUDGMENTS[15]],
    messages: []
  },
  {
    id: "res-08",
    organizationId: "org-demo-firm-01",
    userId: "user-admin-01",
    title: "Homebuyer right to interest on delayed possession under Section 18 RERA",
    previewQuery: "Can promoter contracts restrict statutory interest rate prescribed under state RERA rules?",
    legalArea: "Real Estate Law",
    createdAt: "2026-07-18T10:00:00Z",
    updatedAt: "2026-07-18T10:04:00Z",
    isSaved: false,
    sources: [DEMO_JUDGMENTS[8]],
    messages: []
  },
  {
    id: "res-09",
    organizationId: "org-demo-firm-01",
    userId: "user-associate-01",
    title: "Admissibility of Secondary Evidence under BSA Section 60",
    previewQuery: "Procedural prerequisites for producing certified electronic extracts under modern evidence law.",
    legalArea: "Law of Evidence (BSA)",
    createdAt: "2026-07-10T14:00:00Z",
    updatedAt: "2026-07-10T14:04:00Z",
    isSaved: false,
    sources: [DEMO_JUDGMENTS[2]],
    messages: []
  },
  {
    id: "res-10",
    organizationId: "org-demo-firm-01",
    userId: "user-advocate-01",
    title: "Blacklisting and administrative fairness under Article 14 of Constitution",
    previewQuery: "Requirements of specific notice regarding intent to debar before blacklisting government contractors.",
    legalArea: "Constitutional & Administrative Law",
    createdAt: "2026-07-02T16:00:00Z",
    updatedAt: "2026-07-02T16:05:00Z",
    isSaved: true,
    sources: [DEMO_JUDGMENTS[0]],
    messages: []
  }
];

// ============================================================================
// AUDIT LOGS FOR DEMO PLATFORM
// ============================================================================
export const DEMO_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: "audit-01",
    organizationId: "org-demo-firm-01",
    userId: "user-advocate-01",
    userEmail: "demo.advocate@nyayaai.test",
    action: "USER_LOGIN",
    details: "Authenticated via secure JWT session from New Delhi (Demo IP)",
    ipAddress: "103.21.244.0",
    timestamp: "2026-09-08T08:30:00Z"
  },
  {
    id: "audit-02",
    organizationId: "org-demo-firm-01",
    userId: "user-advocate-01",
    userEmail: "demo.advocate@nyayaai.test",
    action: "RESEARCH_QUERY",
    details: "Executed legal research query on BNSS bail discretion standards",
    ipAddress: "103.21.244.0",
    timestamp: "2026-09-08T08:32:15Z"
  },
  {
    id: "audit-03",
    organizationId: "org-demo-firm-01",
    userId: "user-advocate-01",
    userEmail: "demo.advocate@nyayaai.test",
    action: "CITATION_VERIFIED",
    details: "Verified citation 2024 SCC OnLine SC 892 against demo knowledge base: VERIFIED",
    ipAddress: "103.21.244.0",
    timestamp: "2026-09-08T08:34:00Z"
  },
  {
    id: "audit-04",
    organizationId: "org-demo-firm-01",
    userId: "user-admin-01",
    userEmail: "demo.admin@nyayaai.test",
    action: "USER_LOGIN",
    details: "Administrator session established from Mumbai",
    ipAddress: "49.36.12.18",
    timestamp: "2026-09-08T07:45:00Z"
  },
  {
    id: "audit-05",
    organizationId: "org-demo-firm-01",
    userId: "user-admin-01",
    userEmail: "demo.admin@nyayaai.test",
    action: "ADMIN_ACTION",
    details: "Re-indexed demonstration knowledge base vectors (22 statutes, 22 judgments)",
    ipAddress: "49.36.12.18",
    timestamp: "2026-09-08T07:50:00Z"
  }
];

// Helper to search demonstration authorities by query keywords
export function searchMockAuthorities(query: string): LegalSource[] {
  const q = query.toLowerCase();
  
  if (q.includes("bail") || q.includes("arrest") || q.includes("custody") || q.includes("criminal") || q.includes("bnss") || q.includes("bns")) {
    return [DEMO_JUDGMENTS[1], DEMO_JUDGMENTS[5], DEMO_JUDGMENTS[10], DEMO_JUDGMENTS[15]];
  }
  if (q.includes("arbitrat") || q.includes("award") || q.includes("mediat") || q.includes("section 34") || q.includes("section 11")) {
    return [DEMO_JUDGMENTS[3], DEMO_JUDGMENTS[17], DEMO_JUDGMENTS[0]];
  }
  if (q.includes("cyber") || q.includes("data") || q.includes("evidence") || q.includes("electronic") || q.includes("bsa") || q.includes("65b")) {
    return [DEMO_JUDGMENTS[2], DEMO_JUDGMENTS[6]];
  }
  if (q.includes("insolven") || q.includes("ibc") || q.includes("nclt") || q.includes("cirp") || q.includes("moratorium")) {
    return [DEMO_JUDGMENTS[7]];
  }
  if (q.includes("patent") || q.includes("trademark") || q.includes("copyright") || q.includes("ip")) {
    return [DEMO_JUDGMENTS[6], DEMO_JUDGMENTS[14]];
  }
  if (q.includes("rera") || q.includes("builder") || q.includes("homebuyer") || q.includes("property")) {
    return [DEMO_JUDGMENTS[8], DEMO_JUDGMENTS[18], DEMO_JUDGMENTS[21]];
  }
  if (q.includes("tax") || q.includes("gst") || q.includes("income") || q.includes("customs")) {
    return [DEMO_JUDGMENTS[19], DEMO_JUDGMENTS[20]];
  }

  // Default relevant set
  return [DEMO_JUDGMENTS[0], DEMO_JUDGMENTS[1], DEMO_JUDGMENTS[3], DEMO_JUDGMENTS[2]];
}
